[workspace]
resolver = "2"
members = ["rust/crates/rusty-d20"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
gtk = "0.18"
rusty-engine = { path = "../rusty-engine/rust/crates/rusty-engine" }
winit = "0.30"

[workspace.lints.rust]
unsafe_code = "forbid"
