// Generated by tools/scripts/gen-eslint-boundaries.mjs. Do not hand-edit.
import nx from '@nx/eslint-plugin';

const depConstraints = [
  {
    "sourceTag": "type:app",
    "onlyDependOnLibsWithTags": [
      "type:lib",
      "type:feature"
    ]
  },
  {
    "sourceTag": "type:lib",
    "onlyDependOnLibsWithTags": [
      "type:lib"
    ]
  },
  {
    "sourceTag": "type:feature",
    "onlyDependOnLibsWithTags": [
      "type:lib"
    ]
  },
  {
    "sourceTag": "type:testing",
    "onlyDependOnLibsWithTags": [
      "type:app",
      "type:lib",
      "type:feature",
      "type:testing"
    ]
  },
  {
    "sourceTag": "scope:protocol",
    "onlyDependOnLibsWithTags": []
  },
  {
    "sourceTag": "scope:platform",
    "onlyDependOnLibsWithTags": []
  },
  {
    "sourceTag": "scope:transport",
    "onlyDependOnLibsWithTags": [
      "scope:protocol",
      "scope:platform"
    ]
  },
  {
    "sourceTag": "scope:domain",
    "onlyDependOnLibsWithTags": [
      "scope:protocol"
    ]
  },
  {
    "sourceTag": "scope:store",
    "onlyDependOnLibsWithTags": [
      "scope:protocol",
      "scope:platform",
      "scope:transport",
      "scope:domain"
    ]
  },
  {
    "sourceTag": "scope:renderer",
    "onlyDependOnLibsWithTags": [
      "scope:domain",
      "scope:components",
      "scope:theme"
    ]
  },
  {
    "sourceTag": "scope:components",
    "onlyDependOnLibsWithTags": [
      "scope:theme"
    ]
  },
  {
    "sourceTag": "scope:feature",
    "onlyDependOnLibsWithTags": [
      "scope:protocol",
      "scope:platform",
      "scope:domain",
      "scope:store",
      "scope:renderer",
      "scope:components",
      "scope:theme"
    ]
  },
  {
    "sourceTag": "scope:shell",
    "onlyDependOnLibsWithTags": [
      "scope:shell",
      "scope:feature",
      "scope:platform",
      "scope:store",
      "scope:theme"
    ]
  },
  {
    "sourceTag": "scope:theme",
    "onlyDependOnLibsWithTags": []
  },
  {
    "sourceTag": "scope:testing-fixtures",
    "onlyDependOnLibsWithTags": [
      "scope:protocol",
      "scope:platform",
      "scope:transport",
      "scope:domain",
      "scope:store",
      "scope:renderer",
      "scope:components",
      "scope:feature",
      "scope:shell",
      "scope:theme"
    ]
  }
];

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: ['dist/**', 'coverage/**', 'node_modules/**', 'tmp/**']
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.mts', '**/*.mjs'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints,
          enforceBuildableLibDependency: false
        }
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error'
    }
  }
];
