// GENERATED by `cargo run -p rusty-d20 --bin rusty-d20-rules-contract`. Do not hand-edit.

export const D20_CANDIDATE_SCHEMA_VERSION = 4 as const;
export const D20_ID_PATTERN = "^[a-z0-9._-]+$" as const;
export const D20_LIMITS = Object.freeze({
maxIdBytes: 64,
maxDefinitionsPerKind: 64,
maxDamageDice: 32,
maxDamageDieSides: 1000,
maxEffectDurationTurns: 10000,
maxActionTags: 16,
maxActivationCosts: 4,
maxConditionClauses: 8,
maxImplementTags: 16,
maxTacticalRange: 32,
maxForcedMovement: 6,
maxTacticalBoardWidth: 16,
maxTacticalBoardHeight: 16,
maxTacticalBoardCells: 256,
maxActionTargets: 12,
maxAdventuresPerPackage: 16,
maxAdventureEntries: 64,
maxAuthoredTextBytes: 512,
} as const);

export type D20Id = string;

export type AbilityCandidate = { id: D20Id, minimum: number, maximum: number, };

export type DefenseCandidate = { id: D20Id, base: number, abilities: Array<D20Id>, };

export type ActivationTimingCandidate = "action" | "reaction";

export type ActivationBudgetCandidate = { id: D20Id, timing: ActivationTimingCandidate, initial: number, };

export type DamageTypeCandidate = { id: D20Id, };

export type ResourceCandidate = { id: D20Id, maximum: number, };

export type ArmorCandidate = { id: D20Id, defense: D20Id, bonus: number, slot: D20Id, };

export type ImplementCandidate = { id: D20Id, slot: D20Id, tags: Array<D20Id>, ability: D20Id, defense: D20Id, damage: DamageCandidate, range: number, };

export type ConditionClauseCandidate = { "kind": "forbid-movement" } | { "kind": "forbid-action-tag", tag: D20Id, } | { "kind": "attack-penalty", amount: number, };

export type EffectCandidate = { id: D20Id, defense: D20Id | null, defenseBonus: number, durationTurns: number, conditions: Array<ConditionClauseCandidate>, };

export type DamageCandidate = { kind: D20Id, dice: number, sides: number, bonus: number, };

export type ReactionCandidate = { id: D20Id, defense: D20Id, bonus: number, resource: D20Id, cost: number, activationCosts: Array<ActivationCostCandidate>, effect: D20Id, };

export type ActivationCostCandidate = { budget: D20Id, amount: number, };

export type ActionTargetKindCandidate = "participant" | "cell";

export type ActionTargetTeamCandidate = "hostile" | "ally" | "self-only" | "any";

export type ActionLineOfEffectCandidate = "required" | "ignored";

export type ActionTargetCandidate = { kind: ActionTargetKindCandidate, team: ActionTargetTeamCandidate, maximumTargets: number, lineOfEffect: ActionLineOfEffectCandidate, };

export type ActionAttackCandidate = { "kind": "fixed", ability: D20Id, defense: D20Id, damage: DamageCandidate, range: number, } | { "kind": "implement", implement: D20Id, };

export type ActionCandidate = { id: D20Id, tags: Array<D20Id>, activationCosts: Array<ActivationCostCandidate>, target: ActionTargetCandidate, attack: ActionAttackCandidate, effect: D20Id | null, forcedMovement: number, };

export type CharacterAbilityCandidate = { ability: D20Id, score: number, };

export type CharacterResourceCandidate = { resource: D20Id, current: number, };

export type CharacterAffinityKindCandidate = "resistant" | "vulnerable";

export type CharacterAffinityCandidate = { damageType: D20Id, affinity: CharacterAffinityKindCandidate, };

export type CharacterTemplateCandidate = { id: D20Id, entityId: number, name: string, title: string, level: number, vitality: number, inventoryCapacity: number, abilities: Array<CharacterAbilityCandidate>, resources: Array<CharacterResourceCandidate>, actions: Array<D20Id>, reactions: Array<D20Id>, affinities: Array<CharacterAffinityCandidate>, };

export type StorageCandidate = { id: D20Id, entityId: number, name: string, capacity: number, };

export type ItemRarityCandidate = "common" | "uncommon" | "rare" | "epic";

export type EquipmentReferenceCandidate = { "kind": "armor", armor: D20Id, } | { "kind": "implement", implement: D20Id, };

export type ItemInstanceCandidate = { id: D20Id, entityId: number, name: string, equipment: EquipmentReferenceCandidate, owner: D20Id, icon: string, rarity: ItemRarityCandidate, equipped: boolean, };

export type EncounterOutcomeCandidate = { title: string, summary: string, logSource: string, logText: string, logDetails: Array<string>, rewardItem: D20Id | null, rewardLabel: string | null, recoveryVitality: number | null, };

export type EncounterFactionCandidate = "party" | "opposition";

export type EncounterParticipantCandidate = { character: D20Id, faction: EncounterFactionCandidate, };

export type TacticalPlacementCandidate = { character: D20Id, x: number, y: number, };

export type TacticalBoardCandidate = { width: number, height: number, rows: Array<string>, placements: Array<TacticalPlacementCandidate>, };

export type EncounterCandidate = { id: D20Id, title: string, summary: string, roster: Array<EncounterParticipantCandidate>, board: TacticalBoardCandidate, availableFromCamp: boolean, introductionSource: string, introductionText: string, introductionDetails: Array<string>, victory: EncounterOutcomeCandidate, defeat: EncounterOutcomeCandidate, };

export type DungeonFacingCandidate = "north" | "east" | "south" | "west";

export type DungeonEncounterCandidate = { encounter: D20Id, x: number, y: number, };

export type DungeonLandmarkCandidate = { id: D20Id, x: number, y: number, title: string, text: string, };

export type DungeonCandidate = { title: string, wallStyle: D20Id, width: number, height: number, rows: Array<string>, startX: number, startY: number, checkpointX: number, checkpointY: number, startFacing: DungeonFacingCandidate, encounters: Array<DungeonEncounterCandidate>, landmarks: Array<DungeonLandmarkCandidate>, };

export type AdventureCandidate = { id: D20Id, title: string, default: boolean, selectable: boolean, party: Array<D20Id>, characters: Array<D20Id>, campStorage: D20Id, storage: Array<D20Id>, items: Array<D20Id>, encounters: Array<D20Id>, dungeon: DungeonCandidate, startSource: string, startText: string, startDetails: Array<string>, };

export type D20RulesCandidate = { schemaVersion: number, abilities: Array<AbilityCandidate>, defenses: Array<DefenseCandidate>, activationBudgets: Array<ActivationBudgetCandidate>, damageTypes: Array<DamageTypeCandidate>, resources: Array<ResourceCandidate>, armors: Array<ArmorCandidate>, implements: Array<ImplementCandidate>, effects: Array<EffectCandidate>, reactions: Array<ReactionCandidate>, actions: Array<ActionCandidate>, characterTemplates: Array<CharacterTemplateCandidate>, storage: Array<StorageCandidate>, itemInstances: Array<ItemInstanceCandidate>, encounters: Array<EncounterCandidate>, adventures: Array<AdventureCandidate>, };
