// GENERATED by `cargo run -p rusty-d20 --bin rusty-d20-rules-contract`. Do not hand-edit.

export const D20_CANDIDATE_SCHEMA_VERSION = 1 as const;
export const D20_ID_PATTERN = "^[a-z0-9._-]+$" as const;
export const D20_LIMITS = Object.freeze({
maxIdBytes: 64,
maxDefinitionsPerKind: 64,
maxDamageDice: 32,
maxDamageDieSides: 1000,
maxEffectDurationTurns: 10000,
} as const);

export type D20Id = string;

export type AbilityCandidate = { id: D20Id, minimum: number, maximum: number, };

export type DefenseCandidate = { id: D20Id, base: number, ability: D20Id, };

export type DamageTypeCandidate = { id: D20Id, };

export type ResourceCandidate = { id: D20Id, maximum: number, };

export type ArmorCandidate = { id: D20Id, defense: D20Id, bonus: number, slot: D20Id, };

export type EffectCandidate = { id: D20Id, defense: D20Id | null, defenseBonus: number, durationTurns: number, };

export type DamageCandidate = { kind: D20Id, dice: number, sides: number, bonus: number, };

export type ReactionCandidate = { id: D20Id, defense: D20Id, bonus: number, resource: D20Id, cost: number, effect: D20Id, };

export type ActionCandidate = { id: D20Id, ability: D20Id, defense: D20Id, damage: DamageCandidate, effect: D20Id | null, };

export type D20RulesCandidate = { schemaVersion: number, abilities: Array<AbilityCandidate>, defenses: Array<DefenseCandidate>, damageTypes: Array<DamageTypeCandidate>, resources: Array<ResourceCandidate>, armors: Array<ArmorCandidate>, effects: Array<EffectCandidate>, reactions: Array<ReactionCandidate>, actions: Array<ActionCandidate>, };
