import { defineD20Module } from '@rusty-d20/rules-authoring';

export const catalogProbeModule = defineD20Module(
  {
    id: 'catalog-probe-adventure',
    path: 'rules/packages/starter-ruleset/src/content/adventures/catalog_probe.ts',
  },
  ({ adventure }) => ({
    adventures: [
      adventure(10, {
        id: 'catalog-probe',
        title: 'Authored Catalog Probe',
        default: false,
        selectable: false,
        party: ['mara-venn', 'ilyra-fen', 'corin-ash', 'veyra-quill'],
        characters: [
          'iron-warden',
          'gate-skirmisher',
          'mara-venn',
          'ilyra-fen',
          'corin-ash',
          'veyra-quill',
        ],
        campStorage: 'camp-stash',
        storage: ['camp-stash'],
        items: [
          'mara-buckler',
          'mara-chain',
          'spare-buckler',
          'warden-chain',
          'warden-blade',
          'mara-blade',
          'warden-bow',
          'mara-bow',
          'ilyra-chain',
          'ilyra-blade',
          'ilyra-bow',
          'corin-chain',
          'corin-blade',
          'corin-bow',
          'veyra-chain',
          'veyra-blade',
          'veyra-bow',
          'skirmisher-blade',
          'skirmisher-bow',
          'skirmisher-chain',
        ],
        encounters: ['iron-warden'],
        dungeon: {
          title: 'Catalog Probe',
          wallStyle: 'probe',
          width: 5,
          height: 5,
          rows: ['#####', '#...#', '#.#.#', '#...#', '#####'],
          startX: 1,
          startY: 1,
          startCheckpoint: 'probe-camp',
          startFacing: 'east',
          encounters: [{ encounter: 'iron-warden', x: 3, y: 3 }],
          landmarks: [],
          doors: [],
          treasures: [],
          checkpoints: [
            {
              id: 'probe-camp',
              x: 1,
              y: 1,
              title: 'Probe camp',
              text: 'The content-only probe can return here safely.',
            },
          ],
        },
        startSource: 'Adventure',
        startText: 'The content-only catalog probe is ready.',
        startDetails: [
          'This non-default adventure reuses admitted primitives without Rust orchestration changes.',
        ],
        completion: {
          source: 'Adventure',
          victoryTitle: 'Probe complete',
          victoryText: 'The content-only probe reached its terminal state.',
          defeatTitle: 'Probe ended',
          defeatText: 'The content-only probe ended after defeat.',
          details: ['No production adventure depends on this hidden probe.'],
        },
      }),
    ],
  }),
);
