import { defineD20Module } from '@rusty-d20/rules-authoring';

export const wardenLoadoutModule = defineD20Module(
  {
    id: 'warden-loadout',
    path: 'rules/packages/starter-ruleset/src/content/adventures/warden_loadout.ts',
  },
  ({ itemInstance, storage }) => ({
    storage: [
      storage(10, {
        id: 'camp-stash',
        entityId: 103,
        name: 'Camp stash',
        capacity: 8,
      }),
    ],
    itemInstances: [
      itemInstance(18, {
        id: 'warden-chain',
        entityId: 201,
        name: 'Warden chain armor',
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'iron-warden',
        icon: '🛡️',
        rarity: 'uncommon',
        equipped: true,
      }),
      itemInstance(28, {
        id: 'mara-chain',
        entityId: 202,
        name: "Mara's chain armor",
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'mara-venn',
        icon: '🛡️',
        rarity: 'uncommon',
        equipped: true,
      }),
      itemInstance(38, {
        id: 'mara-buckler',
        entityId: 203,
        name: "Mara's buckler",
        equipment: { kind: 'armor', armor: 'buckler' },
        owner: 'mara-venn',
        icon: '◈',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(48, {
        id: 'spare-buckler',
        entityId: 204,
        name: 'Spare buckler',
        equipment: { kind: 'armor', armor: 'buckler' },
        owner: 'camp-stash',
        icon: '◈',
        rarity: 'common',
        equipped: false,
      }),
      itemInstance(58, {
        id: 'warden-blade',
        entityId: 205,
        name: "Warden's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'iron-warden',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(68, {
        id: 'mara-blade',
        entityId: 206,
        name: "Mara's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'mara-venn',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(78, {
        id: 'warden-bow',
        entityId: 207,
        name: "Warden's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'iron-warden',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(88, {
        id: 'mara-bow',
        entityId: 208,
        name: "Mara's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'mara-venn',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
    ],
  }),
);
