import { defineD20Module } from "@rusty-d20/rules-authoring";

const completeResources = [
  { resource: "focus", current: 3 },
  { resource: "guard", current: 2 },
  { resource: "resolve-points", current: 2 },
] as const;

export const wardenCastModule = defineD20Module(
  {
    id: "warden-cast",
    path: "rules/packages/starter-ruleset/src/content/adventures/warden_cast.ts",
  },
  ({ characterTemplate, feature }) => ({
    features: [
      feature(16, {
        id: "arcane-composure",
        label: "Arcane Composure",
        description:
          "Veyra holds a spell pattern steady even when the line closes around her.",
      }),
      feature(22, {
        id: "coordinated-flanker",
        label: "Coordinated Flanker",
        description:
          "Training with a nearby ally turns an opening into a decisive attack.",
      }),
      feature(28, {
        id: "hold-the-line",
        label: "Hold the Line",
        description:
          "Mara is practiced at controlling a threatened position under pressure.",
      }),
      feature(34, {
        id: "pathfinder-instinct",
        label: "Pathfinder Instinct",
        description:
          "Ilyra reads broken ground and dangerous approaches before committing the party.",
      }),
      feature(40, {
        id: "pattern-reader",
        label: "Pattern Reader",
        description:
          "Repeated defenses reveal the small inconsistencies Veyra can exploit.",
      }),
      feature(46, {
        id: "signal-discipline",
        label: "Signal Discipline",
        description:
          "Corin keeps the expedition coordinated when sight lines and plans collapse.",
      }),
      feature(52, {
        id: "warden-training",
        label: "Warden Training",
        description:
          "Gate wardens drill to defend fixed ground and answer threats as a unit.",
      }),
      feature(58, {
        id: "watchful-response",
        label: "Watchful Response",
        description:
          "Corin notices a shift in hostile intent early enough to warn an ally.",
      }),
    ],
    characterTemplates: [
      characterTemplate(16, {
        id: "mara-venn",
        entityId: 101,
        name: "Mara Venn",
        title: "Ward Anchor",
        level: 1,
        experience: 900,
        vitality: 24,
        inventoryCapacity: 4,
        abilities: [
          { ability: "acuity", score: 12 },
          { ability: "conviction", score: 12 },
          { ability: "finesse", score: 18 },
          { ability: "intellect", score: 10 },
          { ability: "might", score: 18 },
          { ability: "spirit", score: 10 },
        ],
        resources: [...completeResources],
        actions: [
          "longsword-strike",
          "precise-shot",
          "pin-in-place",
          "disrupt",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["coordinated-flanker", "hold-the-line"],
      }),
      characterTemplate(35, {
        id: "ilyra-fen",
        entityId: 104,
        name: "Ilyra Fen",
        title: "Pathfinder",
        level: 1,
        experience: 760,
        vitality: 18,
        inventoryCapacity: 4,
        abilities: [
          { ability: "acuity", score: 16 },
          { ability: "conviction", score: 12 },
          { ability: "finesse", score: 16 },
          { ability: "intellect", score: 12 },
          { ability: "might", score: 12 },
          { ability: "spirit", score: 14 },
        ],
        resources: [...completeResources],
        actions: [
          "precise-shot",
          "longsword-strike",
          "disrupt",
          "pin-in-place",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["coordinated-flanker", "pathfinder-instinct"],
      }),
      characterTemplate(54, {
        id: "corin-ash",
        entityId: 105,
        name: "Corin Ash",
        title: "Signal Guide",
        level: 1,
        experience: 680,
        vitality: 20,
        inventoryCapacity: 4,
        abilities: [
          { ability: "acuity", score: 12 },
          { ability: "conviction", score: 16 },
          { ability: "finesse", score: 13 },
          { ability: "intellect", score: 14 },
          { ability: "might", score: 12 },
          { ability: "spirit", score: 16 },
        ],
        resources: [...completeResources],
        actions: [
          "longsword-strike",
          "disrupt",
          "precise-shot",
          "pin-in-place",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["signal-discipline", "watchful-response"],
      }),
      characterTemplate(73, {
        id: "veyra-quill",
        entityId: 106,
        name: "Veyra Quill",
        title: "Field Shaper",
        level: 1,
        experience: 820,
        vitality: 16,
        inventoryCapacity: 4,
        abilities: [
          { ability: "acuity", score: 14 },
          { ability: "conviction", score: 14 },
          { ability: "finesse", score: 12 },
          { ability: "intellect", score: 18 },
          { ability: "might", score: 10 },
          { ability: "spirit", score: 16 },
        ],
        resources: [...completeResources],
        actions: [
          "disrupt",
          "precise-shot",
          "pin-in-place",
          "longsword-strike",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["arcane-composure", "pattern-reader"],
      }),
      characterTemplate(92, {
        id: "gate-skirmisher",
        entityId: 107,
        name: "Gate Skirmisher",
        title: "Warden Pathfinder",
        level: 1,
        experience: 0,
        vitality: 18,
        inventoryCapacity: 3,
        abilities: [
          { ability: "acuity", score: 14 },
          { ability: "conviction", score: 10 },
          { ability: "finesse", score: 17 },
          { ability: "intellect", score: 10 },
          { ability: "might", score: 12 },
          { ability: "spirit", score: 12 },
        ],
        resources: [...completeResources],
        actions: [
          "precise-shot",
          "disrupt",
          "longsword-strike",
          "pin-in-place",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["warden-training"],
      }),
      characterTemplate(111, {
        id: "iron-warden",
        entityId: 102,
        name: "Iron Warden",
        title: "Gate Sentinel",
        level: 1,
        experience: 0,
        vitality: 24,
        inventoryCapacity: 3,
        abilities: [
          { ability: "acuity", score: 10 },
          { ability: "conviction", score: 12 },
          { ability: "finesse", score: 14 },
          { ability: "intellect", score: 12 },
          { ability: "might", score: 14 },
          { ability: "spirit", score: 14 },
        ],
        resources: [...completeResources],
        actions: [
          "longsword-strike",
          "precise-shot",
          "pin-in-place",
          "disrupt",
        ],
        reactions: ["parry"],
        affinities: [{ damageType: "impact", affinity: "resistant" }],
        features: ["hold-the-line", "warden-training"],
      }),
      characterTemplate(130, {
        id: "gate-sentry",
        entityId: 109,
        name: "Gate Sentry",
        title: "Line Sentry",
        level: 1,
        experience: 0,
        vitality: 16,
        inventoryCapacity: 3,
        abilities: [
          { ability: "acuity", score: 10 },
          { ability: "conviction", score: 12 },
          { ability: "finesse", score: 13 },
          { ability: "intellect", score: 10 },
          { ability: "might", score: 16 },
          { ability: "spirit", score: 12 },
        ],
        resources: [...completeResources],
        actions: [
          "longsword-strike",
          "pin-in-place",
          "precise-shot",
          "disrupt",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["warden-training"],
      }),
      characterTemplate(149, {
        id: "seal-adept",
        entityId: 110,
        name: "Seal Adept",
        title: "Field Adept",
        level: 1,
        experience: 0,
        vitality: 15,
        inventoryCapacity: 3,
        abilities: [
          { ability: "acuity", score: 17 },
          { ability: "conviction", score: 14 },
          { ability: "finesse", score: 12 },
          { ability: "intellect", score: 16 },
          { ability: "might", score: 10 },
          { ability: "spirit", score: 15 },
        ],
        resources: [...completeResources],
        actions: [
          "disrupt",
          "precise-shot",
          "pin-in-place",
          "longsword-strike",
        ],
        reactions: ["parry"],
        affinities: [],
        features: ["arcane-composure"],
      }),
    ],
  }),
);
