import { defineD20Module } from '@rusty-d20/rules-authoring';

export const wardensGateModule = defineD20Module(
  {
    id: 'wardens-gate-adventure',
    path: 'rules/packages/starter-ruleset/src/content/adventures/wardens_gate.ts',
  },
  ({ adventure, encounter }) => ({
    encounters: [
      encounter(10, {
        id: 'iron-warden',
        title: 'The Iron Warden',
        summary: 'Challenge the armored sentinel guarding the mountain pass.',
        roster: [
          { character: 'mara-venn', faction: 'party' },
          { character: 'ilyra-fen', faction: 'party' },
          { character: 'corin-ash', faction: 'party' },
          { character: 'veyra-quill', faction: 'party' },
          { character: 'iron-warden', faction: 'opposition' },
          { character: 'gate-skirmisher', faction: 'opposition' },
        ],
        board: {
          width: 12,
          height: 8,
          rows: [
            '############',
            '#..........#',
            '#..#.......#',
            '#..........#',
            '#....##....#',
            '#..........#',
            '#.......#..#',
            '############',
          ],
          placements: [
            { character: 'mara-venn', x: 7, y: 4 },
            { character: 'ilyra-fen', x: 1, y: 2 },
            { character: 'corin-ash', x: 1, y: 4 },
            { character: 'veyra-quill', x: 2, y: 5 },
            { character: 'iron-warden', x: 8, y: 4 },
            { character: 'gate-skirmisher', x: 10, y: 2 },
          ],
        },
        availableFromCamp: true,
        introductionSource: 'Encounter',
        introductionText:
          "Mara Venn's four-person company faces the Warden patrol.",
        introductionDetails: [
          'Ward Anchor, Pathfinder, Signal Guide, and Field Shaper roles enter one authoritative initiative order.',
          "The Iron Warden and Gate Skirmisher's equipment, resources, and effects remain canonical entity facts.",
        ],
        victory: {
          title: 'The Iron Warden defeated',
          summary:
            'The company prevailed; every member’s remaining vitality and resources carry forward.',
          logSource: 'Victory',
          logText: 'The Iron Warden falls and yields the Warden chain armor.',
          logDetails: [
            'Warden chain armor was unequipped and transferred into canonical camp storage.',
          ],
          rewardItem: 'warden-chain',
          rewardLabel: 'Warden chain armor',
          recoveryVitality: null,
        },
        defeat: {
          title: 'The company was defeated',
          summary:
            'No reward was granted; returning to camp applies bounded recovery.',
          logSource: 'Defeat',
          logText: 'Mara’s company falls and must recover before continuing.',
          logDetails: [
            'Every party participant reached zero vitality; no reward or inventory mutation occurred.',
            'Return to camp applies the explicit bounded recovery consequence.',
          ],
          rewardItem: null,
          rewardLabel: null,
          recoveryVitality: 12,
        },
      }),
      encounter(64, {
        id: 'wardens-reckoning',
        title: "The Warden's Reckoning",
        summary:
          'Face the reawakened sentinel after its gate armor has become part of the camp loadout.',
        roster: [
          { character: 'mara-venn', faction: 'party' },
          { character: 'ilyra-fen', faction: 'party' },
          { character: 'corin-ash', faction: 'party' },
          { character: 'veyra-quill', faction: 'party' },
          { character: 'iron-warden', faction: 'opposition' },
          { character: 'gate-skirmisher', faction: 'opposition' },
        ],
        board: {
          width: 12,
          height: 8,
          rows: [
            '############',
            '#..........#',
            '#.##....##.#',
            '#..........#',
            '#...#..#...#',
            '#..........#',
            '#..........#',
            '############',
          ],
          placements: [
            { character: 'mara-venn', x: 7, y: 5 },
            { character: 'ilyra-fen', x: 1, y: 3 },
            { character: 'corin-ash', x: 2, y: 5 },
            { character: 'veyra-quill', x: 2, y: 6 },
            { character: 'iron-warden', x: 8, y: 5 },
            { character: 'gate-skirmisher', x: 10, y: 2 },
          ],
        },
        availableFromCamp: true,
        introductionSource: 'Encounter',
        introductionText: 'The Iron Warden rises for a final reckoning.',
        introductionDetails: [
          'Rust restores the returning opponent through the bounded vitality track service.',
          'Prior resources, effects, loadout, and the first reward remain authoritative.',
        ],
        victory: {
          title: "The Warden's Reckoning ended",
          summary:
            'Mara completed the authored gate sequence; no duplicate reward was created.',
          logSource: 'Victory',
          logText:
            'The reawakened sentinel yields and the mountain pass is secure.',
          logDetails: [
            'The ordered campaign recorded its second distinct encounter outcome.',
            'The original Warden chain reward remains the only canonical reward instance.',
          ],
          rewardItem: null,
          rewardLabel: null,
          recoveryVitality: null,
        },
        defeat: {
          title: 'Mara fell at the reckoning',
          summary:
            'The authored sequence still completes; camp applies bounded recovery without a reward.',
          logSource: 'Defeat',
          logText: 'Mara withdraws from the final reckoning.',
          logDetails: [
            'No duplicate reward or inventory mutation occurred.',
            'Return to camp applies the explicit bounded recovery consequence.',
          ],
          rewardItem: null,
          rewardLabel: null,
          recoveryVitality: 12,
        },
      }),
    ],
    adventures: [
      adventure(52, {
        id: 'wardens-gate',
        title: "The Warden's Gate",
        default: true,
        selectable: true,
        party: ['mara-venn', 'ilyra-fen', 'corin-ash', 'veyra-quill'],
        characters: [
          'mara-venn',
          'ilyra-fen',
          'corin-ash',
          'veyra-quill',
          'iron-warden',
          'gate-skirmisher',
        ],
        campStorage: 'camp-stash',
        storage: ['camp-stash'],
        items: [
          'warden-chain',
          'mara-chain',
          'mara-buckler',
          'spare-buckler',
          'warden-blade',
          'mara-blade',
          'warden-bow',
          'mara-bow',
          'ilyra-chain',
          'ilyra-blade',
          'ilyra-bow',
          'corin-chain',
          'corin-blade',
          'corin-bow',
          'veyra-chain',
          'veyra-blade',
          'veyra-bow',
          'skirmisher-chain',
          'skirmisher-blade',
          'skirmisher-bow',
        ],
        encounters: ['iron-warden', 'wardens-reckoning'],
        dungeon: {
          title: "Warden's Gate Pass",
          wallStyle: 'mountain-fortress',
          width: 11,
          height: 7,
          rows: [
            '###########',
            '#.........#',
            '#.#####.#.#',
            '#.....#.#.#',
            '#####.#.#.#',
            '#.........#',
            '###########',
          ],
          startX: 1,
          startY: 1,
          checkpointX: 1,
          checkpointY: 1,
          startFacing: 'east',
          encounters: [
            { encounter: 'iron-warden', x: 9, y: 1 },
            { encounter: 'wardens-reckoning', x: 1, y: 5 },
          ],
          landmarks: [
            {
              id: 'gate-murder-holes',
              x: 5,
              y: 1,
              title: 'Silent murder holes',
              text: 'Arrow slits watch the pass, but no bowstring answers your steps.',
            },
            {
              id: 'warden-seal',
              x: 5,
              y: 5,
              title: 'The broken seal',
              text: 'A split iron seal marks the sentinel’s final redoubt.',
            },
          ],
        },
        startSource: 'Adventure',
        startText: "Mara Venn prepares at the Warden's Gate camp.",
        startDetails: [
          'Ruleweaver foundation + Steel Guard authored packages compiled by Rust.',
          'The Ward Anchor, Pathfinder, Signal Guide, and Field Shaper each own canonical equipment and resources.',
          'Two Warden opponents and four party members form one bounded authoritative initiative lifecycle.',
        ],
      }),
    ],
  }),
);
