import { defineD20Module } from '@rusty-d20/rules-authoring';

const completeResources = [
  { resource: 'focus', current: 3 },
  { resource: 'guard', current: 2 },
  { resource: 'resolve-points', current: 2 },
] as const;

export const wardenCastModule = defineD20Module(
  {
    id: 'warden-cast',
    path: 'rules/packages/starter-ruleset/src/content/adventures/warden_cast.ts',
  },
  ({ characterTemplate }) => ({
    characterTemplates: [
      characterTemplate(16, {
        id: 'mara-venn',
        entityId: 101,
        name: 'Mara Venn',
        title: 'Ward Anchor',
        level: 1,
        vitality: 24,
        inventoryCapacity: 4,
        abilities: [
          { ability: 'acuity', score: 12 },
          { ability: 'conviction', score: 12 },
          { ability: 'finesse', score: 18 },
          { ability: 'intellect', score: 10 },
          { ability: 'might', score: 18 },
          { ability: 'spirit', score: 10 },
        ],
        resources: [...completeResources],
        actions: [
          'longsword-strike',
          'precise-shot',
          'pin-in-place',
          'disrupt',
        ],
        reactions: ['parry'],
        affinities: [],
      }),
      characterTemplate(35, {
        id: 'ilyra-fen',
        entityId: 104,
        name: 'Ilyra Fen',
        title: 'Pathfinder',
        level: 1,
        vitality: 18,
        inventoryCapacity: 4,
        abilities: [
          { ability: 'acuity', score: 16 },
          { ability: 'conviction', score: 12 },
          { ability: 'finesse', score: 16 },
          { ability: 'intellect', score: 12 },
          { ability: 'might', score: 12 },
          { ability: 'spirit', score: 14 },
        ],
        resources: [...completeResources],
        actions: [
          'precise-shot',
          'longsword-strike',
          'disrupt',
          'pin-in-place',
        ],
        reactions: ['parry'],
        affinities: [],
      }),
      characterTemplate(54, {
        id: 'corin-ash',
        entityId: 105,
        name: 'Corin Ash',
        title: 'Signal Guide',
        level: 1,
        vitality: 20,
        inventoryCapacity: 4,
        abilities: [
          { ability: 'acuity', score: 12 },
          { ability: 'conviction', score: 16 },
          { ability: 'finesse', score: 13 },
          { ability: 'intellect', score: 14 },
          { ability: 'might', score: 12 },
          { ability: 'spirit', score: 16 },
        ],
        resources: [...completeResources],
        actions: [
          'longsword-strike',
          'disrupt',
          'precise-shot',
          'pin-in-place',
        ],
        reactions: ['parry'],
        affinities: [],
      }),
      characterTemplate(73, {
        id: 'veyra-quill',
        entityId: 106,
        name: 'Veyra Quill',
        title: 'Field Shaper',
        level: 1,
        vitality: 16,
        inventoryCapacity: 4,
        abilities: [
          { ability: 'acuity', score: 14 },
          { ability: 'conviction', score: 14 },
          { ability: 'finesse', score: 12 },
          { ability: 'intellect', score: 18 },
          { ability: 'might', score: 10 },
          { ability: 'spirit', score: 16 },
        ],
        resources: [...completeResources],
        actions: [
          'disrupt',
          'precise-shot',
          'pin-in-place',
          'longsword-strike',
        ],
        reactions: ['parry'],
        affinities: [],
      }),
      characterTemplate(92, {
        id: 'gate-skirmisher',
        entityId: 107,
        name: 'Gate Skirmisher',
        title: 'Warden Pathfinder',
        level: 1,
        vitality: 18,
        inventoryCapacity: 3,
        abilities: [
          { ability: 'acuity', score: 14 },
          { ability: 'conviction', score: 10 },
          { ability: 'finesse', score: 17 },
          { ability: 'intellect', score: 10 },
          { ability: 'might', score: 12 },
          { ability: 'spirit', score: 12 },
        ],
        resources: [...completeResources],
        actions: [
          'precise-shot',
          'disrupt',
          'longsword-strike',
          'pin-in-place',
        ],
        reactions: ['parry'],
        affinities: [],
      }),
      characterTemplate(111, {
        id: 'iron-warden',
        entityId: 102,
        name: 'Iron Warden',
        title: 'Gate Sentinel',
        level: 1,
        vitality: 24,
        inventoryCapacity: 3,
        abilities: [
          { ability: 'acuity', score: 10 },
          { ability: 'conviction', score: 12 },
          { ability: 'finesse', score: 14 },
          { ability: 'intellect', score: 12 },
          { ability: 'might', score: 14 },
          { ability: 'spirit', score: 14 },
        ],
        resources: [...completeResources],
        actions: [
          'longsword-strike',
          'precise-shot',
          'pin-in-place',
          'disrupt',
        ],
        reactions: ['parry'],
        affinities: [{ damageType: 'impact', affinity: 'resistant' }],
      }),
    ],
  }),
);
