import { defineD20Module } from '@rusty-d20/rules-authoring';

export const wardenLoadoutModule = defineD20Module(
  {
    id: 'warden-loadout',
    path: 'rules/packages/starter-ruleset/src/content/adventures/warden_loadout.ts',
  },
  ({ itemInstance, storage }) => ({
    storage: [
      storage(10, {
        id: 'camp-stash',
        entityId: 103,
        name: 'Camp stash',
        capacity: 16,
      }),
    ],
    itemInstances: [
      itemInstance(18, {
        id: 'warden-chain',
        entityId: 201,
        name: 'Warden chain armor',
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'iron-warden',
        icon: '🛡️',
        rarity: 'uncommon',
        equipped: true,
      }),
      itemInstance(28, {
        id: 'mara-chain',
        entityId: 202,
        name: "Mara's chain armor",
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'mara-venn',
        icon: '🛡️',
        rarity: 'uncommon',
        equipped: true,
      }),
      itemInstance(38, {
        id: 'mara-buckler',
        entityId: 203,
        name: "Mara's buckler",
        equipment: { kind: 'armor', armor: 'buckler' },
        owner: 'mara-venn',
        icon: '◈',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(48, {
        id: 'spare-buckler',
        entityId: 204,
        name: 'Spare buckler',
        equipment: { kind: 'armor', armor: 'buckler' },
        owner: 'camp-stash',
        icon: '◈',
        rarity: 'common',
        equipped: false,
      }),
      itemInstance(58, {
        id: 'warden-blade',
        entityId: 205,
        name: "Warden's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'iron-warden',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(68, {
        id: 'mara-blade',
        entityId: 206,
        name: "Mara's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'mara-venn',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(78, {
        id: 'warden-bow',
        entityId: 207,
        name: "Warden's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'iron-warden',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(88, {
        id: 'mara-bow',
        entityId: 208,
        name: "Mara's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'mara-venn',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(98, {
        id: 'ilyra-chain',
        entityId: 209,
        name: "Ilyra's chain armor",
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'ilyra-fen',
        icon: '🛡️',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(108, {
        id: 'ilyra-blade',
        entityId: 210,
        name: "Ilyra's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'ilyra-fen',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(118, {
        id: 'ilyra-bow',
        entityId: 211,
        name: "Ilyra's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'ilyra-fen',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(128, {
        id: 'corin-chain',
        entityId: 212,
        name: "Corin's chain armor",
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'corin-ash',
        icon: '🛡️',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(138, {
        id: 'corin-blade',
        entityId: 213,
        name: "Corin's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'corin-ash',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(148, {
        id: 'corin-bow',
        entityId: 214,
        name: "Corin's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'corin-ash',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(158, {
        id: 'veyra-chain',
        entityId: 215,
        name: "Veyra's chain armor",
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'veyra-quill',
        icon: '🛡️',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(168, {
        id: 'veyra-blade',
        entityId: 216,
        name: "Veyra's training blade",
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'veyra-quill',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(178, {
        id: 'veyra-bow',
        entityId: 217,
        name: "Veyra's field bow",
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'veyra-quill',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(188, {
        id: 'skirmisher-chain',
        entityId: 218,
        name: 'Skirmisher chain armor',
        equipment: { kind: 'armor', armor: 'chain-armor' },
        owner: 'gate-skirmisher',
        icon: '🛡️',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(198, {
        id: 'skirmisher-blade',
        entityId: 219,
        name: 'Skirmisher training blade',
        equipment: { kind: 'implement', implement: 'training-blade' },
        owner: 'gate-skirmisher',
        icon: '⚔',
        rarity: 'common',
        equipped: true,
      }),
      itemInstance(208, {
        id: 'skirmisher-bow',
        entityId: 220,
        name: 'Skirmisher field bow',
        equipment: { kind: 'implement', implement: 'field-bow' },
        owner: 'gate-skirmisher',
        icon: '➶',
        rarity: 'common',
        equipped: true,
      }),
    ],
  }),
);
