//! Concrete downstream state and protocol for the Rusty D20 reference game.
//!
//! Rusty Engine supplies reusable mechanisms. This crate owns Rusty D20's
//! product state, transport projection, and—once added—d20 semantics.

#![forbid(unsafe_code)]

pub mod host;

use core_ids::EntityId;
use entity_state::{EntityDefinition, EntityState};
use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Exact reviewed Rusty Engine revision used by this repository.
pub const ENGINE_REVISION: &str = "fb608e323a8b44a55195f5720101224ff37fd5db";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "kebab-case")]
#[ts(rename_all = "kebab-case")]
pub enum RuntimeStatusDto {
    Ready,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct RuntimeReadoutDto {
    pub product: String,
    pub version: String,
    pub engine_revision: String,
    pub status: RuntimeStatusDto,
    pub entity_count: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct HealthDto {
    pub status: String,
    pub version: String,
}

/// The authoritative in-process state owned by the downstream game.
#[derive(Debug)]
pub struct GameRuntime {
    entities: EntityState,
}

impl GameRuntime {
    pub fn bootstrap() -> Result<Self, entity_state::EntityDefinitionError> {
        let entities = EntityState::from_definitions([EntityDefinition::new(
            EntityId::new(1),
            "bootstrap-session",
        )])?;
        Ok(Self { entities })
    }

    pub fn readout(&self) -> RuntimeReadoutDto {
        RuntimeReadoutDto {
            product: "Rusty D20".to_owned(),
            version: env!("CARGO_PKG_VERSION").to_owned(),
            engine_revision: ENGINE_REVISION.to_owned(),
            status: RuntimeStatusDto::Ready,
            entity_count: u32::try_from(self.entities.total_count())
                .expect("entity-state bounds fit the protocol count"),
        }
    }
}

pub fn generated_typescript() -> String {
    format!(
        "// GENERATED by `cargo run -p rusty-d20 --bin rusty-d20-protocol`. Do not hand-edit.\n\nexport {}\n\nexport {}\n\nexport {}\n",
        RuntimeStatusDto::decl(),
        RuntimeReadoutDto::decl(),
        HealthDto::decl(),
    )
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;

    use super::*;

    #[test]
    fn bootstrap_readout_is_rust_owned_and_engine_backed() {
        let runtime = GameRuntime::bootstrap().expect("bootstrap state");
        assert_eq!(
            runtime.readout(),
            RuntimeReadoutDto {
                product: "Rusty D20".to_owned(),
                version: "0.1.0".to_owned(),
                engine_revision: ENGINE_REVISION.to_owned(),
                status: RuntimeStatusDto::Ready,
                entity_count: 1,
            }
        );
    }

    #[test]
    fn committed_typescript_protocol_matches_rust_owner() {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../libs/protocol/src/generated/api-types.ts");
        let committed = fs::read_to_string(path).expect("committed TypeScript protocol");
        assert_eq!(committed, generated_typescript());
    }

    #[test]
    fn engine_support_crates_are_linked_from_the_reviewed_revision() {
        let _mechanics_limit = gameplay_mechanics::MAX_TRACKS_PER_ENTITY;
        let _rules_limit = gameplay_rules::MAX_RULE_PACKAGES_PER_SET;
        assert_eq!(ENGINE_REVISION.len(), 40);
    }
}
